__default__:
    num_cores: 1
    maxvmem: 4G
distinct_snps:
    num_cores: 1
    maxvmem: 8G
fast_qtl_permutations:
    num_cores: 1
    maxvmem: 6G
fast_qtl:
    num_cores: 1
    maxvmem: 6G
format_gwas:
    num_cores: 1
    maxvmem: 10G
hisat:
    num_cores: 8
    maxvmem: 8G
make_besd:
    num_cores: 1
    maxvmem: 16G
peer:
    num_cores: 1
    maxvmem: 30G
peer_nc:
    num_cores: 1
    maxvmem: 30G
plot_smr:
    num_cores: 1
    maxvmem: 8G
smr:
    num_cores: 10
    maxvmem: 4G
sort_bam:
    num_cores: 8
    maxvmem: 8G
