__default__:
    num_cores: 1
    maxvmem: 4G
summarise_overlaps:
    num_cores: 1
    maxvmem: 6G
fast_qtl_permutations:
    num_cores: 1
    maxvmem: 6G
fast_qtl:
    num_cores: 1
    maxvmem: 6G
sort_bam:
    num_cores: 8
    maxvmem: 8G
hisat:
    num_cores: 8
    maxvmem: 8G
make_besd:
    num_cores: 1
    maxvmem: 40G
cat_smr:
    num_cores: 1
    maxvmem: 20G
prepare_smr:
    num_cores: 1
    maxvmem: 10G
peer:
    num_cores: 1
    maxvmem: 30G
