runs:
    Imputation3: Genotypes/Imputation3
    Imputation4: Genotypes/Imputation4
reference:
    chain_file: /c8000xd3/rnaseq-heath/Ref/Homo_sapiens/GRCh38/hg19ToHg38.over.chain
    genome: /c8000xd3/rnaseq-heath/Ref/Homo_sapiens/GRCh38/NCBI/GRCh38Alt/genome.fa
    rsID: /c8000xd3/rnaseq-heath/Ref/Homo_sapiens/hg19/All_20161121.vcf.gz
    gtf: /c8000xd3/rnaseq-heath/Ref/Homo_sapiens/GRCh38/NCBI/GRCh38Decoy/Annotation/Genes.gencode/genes.gtf
count_data:
    Data/MalevsFemale.complete.txt
sample_info: Data/SampleInfo.txt
genotyping_info: Data/GenotypingInfo.txt
