runs:
    Imputation3: Genotypes/Imputation3
    Imputation4: Genotypes/Imputation4
reference:
    chain_file: /c8000xd3/rnaseq-heath/Ref/Homo_sapiens/GRCh38/hg19ToHg38.over.chain
    genome: /c8000xd3/rnaseq-heath/Ref/Homo_sapiens/GRCh38/NCBI/GRCh38Alt/genome.fa
    rsID: /c8000xd3/rnaseq-heath/Ref/Homo_sapiens/hg19/All_20161121.vcf.gz
    gtf: /c8000xd3/rnaseq-heath/Ref/Homo_sapiens/GRCh38/NCBI/GRCh38Decoy/Annotation/Genes.gencode/genes.gtf
    splice_sites: /c8000xd3/rnaseq-heath/Ref/Homo_sapiens/GRCh38/NCBI/GRCh38Decoy/Annotation/Genes.gencode/splicesites.txt
    index: /c8000xd3/rnaseq-heath/Ref/Homo_sapiens/GRCh38/NCBI/GRCh38Decoy/Sequence/WholeGenomeFasta/genome
count_data: Data/counts_vst.txt
sample_info: Data/SampleInfo.txt
seqfile: Data/sequences.txt
genotyping_info: Data/GenotypingInfo.txt
gtex_samples:
    - Adipose_Subcutaneous
    - Adipose_Visceral_Omentum
    - Adrenal_Gland
    - Artery_Aorta
    - Artery_Coronary
    - Artery_Tibial
    - Brain_Amygdala
    - Brain_Anterior_cingulate_cortex_BA24
    - Brain_Caudate_basal_ganglia
    - Brain_Cerebellar_Hemisphere
    - Brain_Cerebellum
    - Brain_Cortex
    - Brain_Frontal_Cortex_BA9
    - Brain_Hippocampus
    - Brain_Hypothalamus
    - Brain_Nucleus_accumbens_basal_ganglia
    - Brain_Putamen_basal_ganglia
    - Brain_Spinal_cord_cervical_c-1
    - Brain_Substantia_nigra
    - Breast_Mammary_Tissue
    - Cells_EBV-transformed_lymphocytes
    - Cells_Transformed_fibroblasts
    - Colon_Sigmoid
    - Colon_Transverse
    - Esophagus_Gastroesophageal_Junction
    - Esophagus_Mucosa
    - Esophagus_Muscularis
    - Heart_Atrial_Appendage
    - Heart_Left_Ventricle
    - Liver
    - Lung
    - Minor_Salivary_Gland
    - Muscle_Skeletal
    - Nerve_Tibial
    - Ovary
    - Pancreas
    - Pituitary
    - Prostate
    - Skin_Not_Sun_Exposed_Suprapubic
    - Skin_Sun_Exposed_Lower_leg
    - Small_Intestine_Terminal_Ileum
    - Spleen
    - Stomach
    - Testis
    - Thyroid
    - Uterus
    - Vagina
    - Whole_Blood
